# Makefile for busybox
#
# Licensed under the GPL v2, see the file LICENSE in this tarball.

lib-y:=

ifeq ($(CONFIG_PLATFORM_WATCOM386_LINUX),y)
lib-y += poll.o
lib-y += getopt.o
endif

ifeq ($(CONFIG_PLATFORM_WATCOM386_WIN32),y)
lib-y += watcom_stubs.o
lib-y += getopt.o
lib-y += getpagesize.o
lib-y += ftruncate.o
lib-y += wcwidth.o
lib-y += usleep.o
CONFIG_PLATFORM_MINGW32 = y
endif

lib-$(CONFIG_PLATFORM_MINGW32) += env.o
lib-$(CONFIG_PLATFORM_MINGW32) += fnmatch.o
lib-$(CONFIG_PLATFORM_MINGW32) += ioctl.o
lib-$(CONFIG_PLATFORM_MINGW32) += mingw.o
lib-$(CONFIG_PLATFORM_MINGW32) += process.o
lib-$(CONFIG_PLATFORM_MINGW32) += regex.o
lib-$(CONFIG_PLATFORM_MINGW32) += net.o
lib-$(CONFIG_PLATFORM_MINGW32) += poll.o
lib-$(CONFIG_PLATFORM_MINGW32) += popen.o
lib-$(CONFIG_PLATFORM_MINGW32) += statfs.o
lib-$(CONFIG_PLATFORM_MINGW32) += mempcpy.o
lib-$(CONFIG_PLATFORM_MINGW32) += mntent.o
lib-$(CONFIG_PLATFORM_MINGW32) += strptime.o
lib-$(CONFIG_PLATFORM_MINGW32) += system.o
lib-$(CONFIG_PLATFORM_MINGW32) += termios.o
lib-$(CONFIG_PLATFORM_MINGW32) += uname.o
lib-$(CONFIG_PLATFORM_MINGW32) += winansi.o
