# Makefile for busybox
#
# Licensed under the GPL v2, see the file LICENSE in this tarball.

lib-y:=

lib-$(CONFIG_PLATFORM_MINGW32) += env.o
lib-$(CONFIG_PLATFORM_MINGW32) += fnmatch.o
lib-$(CONFIG_PLATFORM_MINGW32) += mingw.o
lib-$(CONFIG_PLATFORM_MINGW32) += process.o
lib-$(CONFIG_PLATFORM_MINGW32) += regex.o
