# Makefile for busybox
#
# Licensed under the GPL v2, see the file LICENSE in this tarball.

lib-y:=

lib-$(CONFIG_PLATFORM_MINGW32) += dirent.o
lib-$(CONFIG_PLATFORM_MINGW32) += dirname.o
lib-$(CONFIG_PLATFORM_MINGW32) += env.o
lib-$(CONFIG_PLATFORM_MINGW32) += flock.o
lib-$(CONFIG_PLATFORM_MINGW32) += fnmatch.o
lib-$(CONFIG_PLATFORM_MINGW32) += fsync.o
lib-$(CONFIG_PLATFORM_MINGW32) += glob.o
lib-$(CONFIG_PLATFORM_MINGW32) += inet_pton.o
lib-$(CONFIG_PLATFORM_MINGW32) += ioctl.o
lib-$(CONFIG_PLATFORM_MINGW32) += mingw.o
lib-$(CONFIG_PLATFORM_MINGW32) += process.o
lib-$(CONFIG_PLATFORM_MINGW32) += match_class.o
lib-$(CONFIG_PLATFORM_MINGW32) += mntent.o
lib-$(CONFIG_PLATFORM_MINGW32) += net.o
lib-$(CONFIG_PLATFORM_MINGW32) += poll.o
lib-$(CONFIG_PLATFORM_MINGW32) += popen.o
lib-$(CONFIG_PLATFORM_MINGW32) += regex.o
lib-$(CONFIG_PLATFORM_MINGW32) += select.o
lib-$(CONFIG_PLATFORM_MINGW32) += statfs.o
lib-$(CONFIG_PLATFORM_MINGW32) += strndup.o
lib-$(CONFIG_PLATFORM_MINGW32) += strptime.o
lib-$(CONFIG_PLATFORM_MINGW32) += strverscmp.o
lib-$(CONFIG_PLATFORM_MINGW32) += system.o
lib-$(CONFIG_PLATFORM_MINGW32) += termios.o
lib-$(CONFIG_PLATFORM_MINGW32) += timegm.o
lib-$(CONFIG_PLATFORM_MINGW32) += uname.o
lib-$(CONFIG_PLATFORM_MINGW32) += winansi.o
