#!/bin/sh

ctype32u=unsigned  # or more specific, like uint32_t
export LC_ALL=C
self=${0##*/}
NL="
"

case ${1-} in -h|--help)
    echo "Usage: $self [path/to/python-wcwidth]"
    echo "Prints a stand alone wcwidth C implementation, with latest Unicode"
    echo "tables imported from a local https://github.com/jquast/wcwidth repo."
    echo "Without the path to a local repo dir, \`.' is assumed."
    echo "Assumes commit 04d6d90c (2023-10-30) or later, where table_zero.py"
    echo "includes zero-width Cf chars - which no longer require manual tests."
    exit 0
esac

[ "${1-}" != -- ] || shift

pwc_root=${1:-.}
pwc_git() { git -C "$pwc_root" "$@"; }

zerowidth_py=$pwc_root/wcwidth/table_zero.py
widewidth_py=$pwc_root/wcwidth/table_wide.py

if ! [ -r "$zerowidth_py" ] || ! [ -r "$widewidth_py" ]; then
    >&2 echo "$self: Error: missing $zerowidth_py or $widewidth_py"
    >&2 echo "Try $self -h"
    exit 1
fi

# latest unicode version from table_wide.py (e.g. from |    '10.0.0': (|
ver=$(grep "^\s*'[0-9]" < "$widewidth_py" | tail -n1 | sed "s/.*'\(.*\)'.*/\1/")

# stdin -> stdout: extract the content of last table (latest spec) from
# wcwidth/table_{wide,zero}.py (from https://github.com/jquast/wcwidth)
last_table() {
    t=
    while read -r line; do  # no IFS= to trim leading whitespaces
        case $line in
            "(0x"* | "# "*)  t=$t$line$NL ;;  # data line or comment
                 "'"[0-9]*)  t= ;;  # new table, reset accumulation
        esac
    done
    printf %s "$t"
}

# stdin -> stdout, e.g.
#   from:      |(0x1e2ae, 0x1e2ae,),  # Toto Sign Rising Tone|
#   to  : |<tab>{0x1e2ae, 0x1e2ae},  /* Toto Sign Rising Tone */|
py_data_to_c() {
    sed -e 's|^(0x|{0x|' -e 's|,),|},|' -e 's|#\(.*\)|/*\1 */|' -e 's|^|\t|'
}

cat << CFILE
/* Stand-alone wcwidth, with Unicode $ver data, generated by $self.
 *
 * Tables imported on $(date -u -I) from https://github.com/jquast/wcwidth
 * commit $(pwc_git describe --tags) ($(pwc_git show --no-patch --format=%ci))
 */

static const $ctype32u WIDTH0[][2] = {
	/* (imported from ${zerowidth_py##*/}) */
$(last_table < "$zerowidth_py" | py_data_to_c)
};  /* WIDTH0 */

static const $ctype32u WIDTH2[][2] = {
	/* (imported from ${widewidth_py##*/}) */
$(last_table < "$widewidth_py" | py_data_to_c)
};  /* WIDTH2 */

static int intable($ctype32u ucs, const $ctype32u table[][2], unsigned len)
{
	unsigned bottom = 0;

	while (bottom != len) {  /* range [bottom..len) */
		$ctype32u mid = (bottom + len) / 2;
		if (ucs > table[mid][1])
			bottom = mid + 1;
		else if (ucs < table[mid][0])
			len = mid;
		else
			return 1;
	}
	return 0;
}

int wcwidth($ctype32u ucs)
{
	/* 0:0, 1..31:-1 (C0), 32..126:1 (isprint), 127..159:-1 (DEL, C1) */
	return ucs < 160 ? (((ucs + 1) & 127) > 32 ? 1 : ucs ? -1 : 0)
	     : intable(ucs, WIDTH0, sizeof WIDTH0 / sizeof *WIDTH0) ? 0
	     : intable(ucs, WIDTH2, sizeof WIDTH2 / sizeof *WIDTH2) + 1;
}

/* end of Stand-alone wcwidth, with Unicode $ver data */
CFILE
